name: My First Workflow
on:                                        # WHEN does this run?
  push:                                    # Every time you push code
    branches: [feature/user-authentication]                       # Only on the 'main' branch
  workflow_dispatch:                       # Also allow manual trigger from GitHub UI

jobs:                                      # WHAT to run
  say-hello:                               # Job name (can be anything)
    runs-on: ubuntu-latest                 # Use GitHub's Ubuntu server

    steps:                                 # Steps run IN ORDER, top to bottom
      - name: Print a message
        run: echo "Hello from GitHub Actions!"

      - name: Show the date
        run: date

      - name: Show system info
        run: uname -a
